set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_DI]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_BCLK]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_MCLK]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_DO]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_RCLK]
set_property IOSTANDARD LVCMOS33 [get_ports iic_0_scl]
set_property IOSTANDARD LVCMOS33 [get_ports iic_0_sda]
set_property IOSTANDARD LVCMOS33 [get_ports led0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n]


set_property PACKAGE_PIN V20 [get_ports I2S_MCLK]
set_property PACKAGE_PIN AA20 [get_ports I2S_DO]
set_property PACKAGE_PIN M22 [get_ports led0]
set_property PACKAGE_PIN M16 [get_ports iic_0_sda]
set_property PACKAGE_PIN M13 [get_ports iic_0_scl]
set_property PACKAGE_PIN U20 [get_ports I2S_BCLK]
set_property PACKAGE_PIN W20 [get_ports I2S_RCLK]
set_property PACKAGE_PIN AA21 [get_ports I2S_DI]
set_property PACKAGE_PIN F15 [get_ports reset_n]
set_property PACKAGE_PIN Y18 [get_ports clk]


set_property PACKAGE_PIN A20 [get_ports button_s1]
set_property IOSTANDARD LVCMOS33 [get_ports button_s1]
set_property PACKAGE_PIN N22 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property PACKAGE_PIN B20 [get_ports button_s2]
set_property IOSTANDARD LVCMOS33 [get_ports button_s2]
set_property PACKAGE_PIN L21 [get_ports led2]
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property PACKAGE_PIN A21 [get_ports button_s3]
set_property IOSTANDARD LVCMOS33 [get_ports button_s3]
set_property PACKAGE_PIN K21 [get_ports led3]
set_property IOSTANDARD LVCMOS33 [get_ports led3]
set_property PACKAGE_PIN B21 [get_ports button_s4]
set_property IOSTANDARD LVCMOS33 [get_ports button_s4]
set_property PACKAGE_PIN K22 [get_ports led4]
set_property IOSTANDARD LVCMOS33 [get_ports led4]
set_property PACKAGE_PIN J22 [get_ports led5]
set_property IOSTANDARD LVCMOS33 [get_ports led5]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property PACKAGE_PIN C18 [get_ports uart_rx]
